repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: end-of-file-fixer
        exclude: .*\.txt
    rev: v4.1.0

  - repo: https://github.com/psf/black
    hooks:
      - id: black
    rev: 21.12b0

  - repo: https://github.com/LilSpazJoekp/docstrfmt
    hooks:
      - id: docstrfmt
        require_serial: true
    rev: v1.4.3

  - repo: https://github.com/pycqa/flake8
    hooks:
      - id: flake8
    rev: 4.0.1

  - repo: https://github.com/ikamensh/flynt/
    hooks:
      - id: flynt
        args:
          - '-ll'
          - '1000'
    rev: '0.69'

  - repo: https://github.com/pycqa/isort
    hooks:
      - id: isort
    rev: 5.10.1

  - repo: https://github.com/pycqa/pydocstyle
    hooks:
      - id: pydocstyle
        files: prawcore/.*
    rev: 6.1.1
